  FIELD CodCta LIKE AC-FAMI.CodCta VALIDATE ~
  FIELD CodFam LIKE AC-FAMI.CodFam VALIDATE ~
  FIELD DesFam LIKE AC-FAMI.DesFam VALIDATE ~
  FIELD PorDep LIKE AC-FAMI.PorDep VALIDATE ~
  FIELD trg-FchAct LIKE AC-FAMI.trg-FchAct VALIDATE ~
  FIELD trg-HraAct LIKE AC-FAMI.trg-HraAct VALIDATE ~
  FIELD trg-Usuario LIKE AC-FAMI.trg-Usuario VALIDATE 
