DEFINE TEMP-TABLE DETALLE  
    FIELDS NUMORD   LIKE PR-ODPC.NUMORD
    FIELDS FCHORD   LIKE PR-ODPC.FCHORD
    FIELDS CODALM   LIKE PR-ODPC.CODALM
    FIELDS FCHVTO   LIKE PR-ODPC.FCHVTO
    FIELDS CODMTE   LIKE PR-ODPCX.CODART
    FIELDS CANPEA   LIKE PR-ODPCX.CANPED FORMAT "->>>999"
    FIELDS CODGAS   LIKE PR-ODPDG.CODGAS
    FIELDS CODPRO   LIKE GN-PROV.CODPRO
    FIELDS CODMAT   LIKE PR-ODPD.CODMAT
    FIELDS CATCONTA LIKE ALMMMATG.CATCONTA
    FIELDS CANPEM   LIKE PR-ODPD.CANPED FORMAT "->>>999"
    FIELDS CANATE   LIKE PR-ODPD.CANATE FORMAT "->>>999"
    FIELDS CANDES   LIKE PR-ODPD.CANDES FORMAT "->>>999"
    FIELDS CTOPRO   LIKE PR-ODPD.CTOPRO FORMAT "->>>999.99"
    FIELDS CTOTOT   LIKE PR-ODPD.CTOTOT FORMAT "->>>999.99".

FOR EACH PR-ODPC NO-LOCK 
    WHERE PR-ODPC.CODCIA = 1 AND PR-ODPC.FCHORD >= 01/01/08, EACH PR-ODPCX NO-LOCK
    WHERE PR-ODPCX.NUMORD = PR-ODPC.NUMORD, FIRST ALMMMATG NO-LOCK
    WHERE ALMMMATG.CODMAT = PR-ODPCX.CODART, EACH PR-ODPDG NO-LOCK
    WHERE PR-ODPDG.NUMORD = PR-ODPCX.NUMORD, FIRST GN-PROV NO-LOCK
    WHERE GN-PROV.CODPRO = PR-ODPDG.CODPRO, FIRST PR-GASTOS NO-LOCK
    WHERE PR-GASTOS.CODGAS = PR-ODPDG.CODGAS, EACH PR-ODPD NO-LOCK
    WHERE PR-ODPD.NUMORD = PR-ODPDG.NUMORD
    BREAK BY PR-ODPC.NUMORD BY PR-ODPCX.CODART BY PR-ODPDG.CODGAS:
    
     CREATE DETALLE.                 
       ASSIGN
           DETALLE.NUMORD = PR-ODPC.NUMORD 
           DETALLE.FCHORD = PR-ODPC.FCHORD 
           DETALLE.CODALM = PR-ODPC.CODALM 
           DETALLE.FCHVTO = PR-ODPC.FCHVTO 
           DETALLE.CODMTE = PR-ODPCX.CODART 
           DETALLE.CANPEA = PR-ODPCX.CANPED 
           DETALLE.CODGAS = PR-ODPDG.CODGAS 
           DETALLE.CODPRO = GN-PROV.CODPRO 
           DETALLE.CODMAT = PR-ODPD.CODMAT
           DETALLE.CATCONTA[1] = ALMMMATG.CATCONTA[1]
           DETALLE.CANPEM = PR-ODPD.CANPED 
           DETALLE.CANATE = PR-ODPD.CANATE 
           DETALLE.CANDES = PR-ODPD.CANDES 
           DETALLE.CTOPRO = PR-ODPD.CTOPRO
           DETALLE.CTOTOT = PR-ODPD.CTOTOT.
   
   DISPLAY 
         DETALLE.NUMORD       
         DETALLE.FCHORD  WHEN FIRST-OF (PR-ODPC.NUMORD)   
         DETALLE.CODALM        COLUMN-LABEL "ALM" WHEN FIRST-OF (PR-ODPC.NUMORD)   
         DETALLE.FCHVTO        COLUMN-LABEL "FCHVTO" WHEN FIRST-OF (PR-ODPC.NUMORD)   
         DETALLE.CODMTE        COLUMN-LABEL "CODMAT" WHEN FIRST-OF (PR-ODPCX.CODART)
         ALMMMATG.DESMAT       COLUMN-LABEL "DESCRIPCION MATERIAL" WHEN FIRST-OF (PR-ODPCX.CODART)
         DETALLE.CANPEA        COLUMN-LABEL "CANPED" WHEN FIRST-OF (PR-ODPCX.CODART)
         PR-ODPC.FLGEST        COLUMN-LABEL "E" WHEN FIRST-OF (PR-ODPCX.CODART)
         DETALLE.CODGAS        COLUMN-LABEL "CODGAS" WHEN FIRST-OF (PR-ODPDG.CODGAS)
         PR-GASTOS.DESGAS      COLUMN-LABEL "DESCRIPCION GASTO" WHEN FIRST-OF (PR-ODPDG.CODGAS)
         DETALLE.CODPRO        COLUMN-LABEL "CODPROV" WHEN FIRST-OF (PR-ODPDG.CODGAS)
         GN-PROV.NOMPRO        COLUMN-LABEL "NOMBRE PROV" WHEN FIRST-OF (PR-ODPDG.CODGAS)
         DETALLE.CODMAT        COLUMN-LABEL "CODMAT" 
         ALMMMATG.DESMAR       COLUMN-LABEL "DESMAR" 
         DETALLE.CATCONTA[1]   COLUMN-LABEL "C.C"  
         DETALLE.CANPEM        COLUMN-LABEL "C.PROCESAR" 
         DETALLE.CANATE        COLUMN-LABEL "C.ATENDIDA" 
         DETALLE.CANDES        COLUMN-LABEL "C.DESPACHADA" 
         DETALLE.CTOPRO        COLUMN-LABEL "CTO. UNIT" 
         DETALLE.CTOTOT        COLUMN-LABEL "CTO.TOTAL"
         WITH STREAM-IO WIDTH 320.

END.



