
/* TABLA TEMPORAL QUE SE CREA PARA ALMACENAR AHI NUESTRAS VARIABLE */

DEFINE VARIABLE ANIO AS INT NO-UNDO.
DEFINE VARIABLE MES AS INT NO-UNDO.

DEFINE TEMP-TABLE DETALLE  
    FIELDS CODVEN LIKE GN-VEN.CODVEN
    FIELDS CODMAT LIKE ALMMMATG.CODMAT
    FIELDS ANIO2005 LIKE EVTVEND.CANXMES FORMAT "->>>>9" EXTENT 12 
    FIELDS ANIO2006 LIKE EVTVEND.CANXMES FORMAT "->>>>9" EXTENT 12
    FIELDS ANIO2007 LIKE EVTVEND.CANXMES FORMAT "->>>>9" EXTENT 12
    FIELDS ANIO2008 LIKE EVTVEND.CANXMES FORMAT "->>>>9" EXTENT 12.
         
  
    FOR EACH EVTVEND NO-LOCK
        WHERE CODCIA = 001 AND
        EVTVEND.CODDIV = "00000" AND
        /*EVTVEND.CODVEN >= "" AND*/
        NROFCH >= 200506 AND NROFCH <= 200806:
          
        FIND DETALLE WHERE
            DETALLE.CODVEN = EVTVEND.CODVEN AND
            DETALLE.CODMAT = EVTVEND.CODMAT
            EXCLUSIVE-LOCK NO-ERROR.
        
        /*SE DA SI ES Q NO HAY REGISTRO CREANDO UNA TABLA VACIA */

        IF NOT AVAILABLE DETALLE THEN DO:
            CREATE DETALLE.                 
            ASSIGN
              DETALLE.CODVEN = EVTVEND.CODVEN
              DETALLE.CODMAT = EVTVEND.CODMAT. 
        END.
        
        ANIO = INTEGER(SUBSTRING(STRING(EVTVEND.NROFCH,"999999"),1,4)).
        MES = INTEGER(SUBSTRING(STRING(EVTVEND.NROFCH,"999999"),5)).
        
        CASE ANIO:
            WHEN 2005 THEN
                DETALLE.ANIO2005[MES] = DETALLE.ANIO2005[MES] + EVTVEND.CANXMES.
            WHEN 2006 THEN
                DETALLE.ANIO2006[MES] = DETALLE.ANIO2006[MES] + EVTVEND.CANXMES.
            WHEN 2007 THEN
                DETALLE.ANIO2007[MES] = DETALLE.ANIO2007[MES] + EVTVEND.CANXMES.
            WHEN 2008 THEN
                DETALLE.ANIO2008[MES] = DETALLE.ANIO2008[MES] + EVTVEND.CANXMES.
        END CASE.

    END.
 
 
  FOR EACH DETALLE, 
    FIRST ALMMMATG NO-LOCK WHERE ALMMMATG.CODCIA = 001
    AND ALMMMATG.CODMAT = DETALLE.CODMAT.
    DISPLAY
        DETALLE.CODVEN COLUMN-LABEL "VEN" 
        DETALLE.CODMAT COLUMN-LABEL "MAT" 
        /*
        ALMMMATG.DESMAT FORMAT "X(20)"
        ALMMMATG.DESMAR FORMAT "X(15)"
        ALMMMATG.UNDBAS COLUMN-LABEL "UB"
        */
        DETALLE.ANIO2005[6]  COLUMN-LABEL "Junio"
        DETALLE.ANIO2005[7]  COLUMN-LABEL "Julio"
        DETALLE.ANIO2005[8]  COLUMN-LABEL "Agosto"
        DETALLE.ANIO2005[9]  COLUMN-LABEL "Setiem"
        DETALLE.ANIO2005[10] COLUMN-LABEL "Octubr"
        DETALLE.ANIO2005[11] COLUMN-LABEL "Noviem"
        DETALLE.ANIO2005[12] COLUMN-LABEL "Diciem"
        DETALLE.ANIO2006[1]  COLUMN-LABEL "Enero"
        DETALLE.ANIO2006[2]  COLUMN-LABEL "Febrer"
        DETALLE.ANIO2006[3]  COLUMN-LABEL "Marzo"
        DETALLE.ANIO2006[4]  COLUMN-LABEL "Abril"
        DETALLE.ANIO2006[5]  COLUMN-LABEL "Mayo"
        DETALLE.ANIO2006[6]  COLUMN-LABEL "Junio"
        DETALLE.ANIO2006[7]  COLUMN-LABEL "Julio"
        DETALLE.ANIO2006[8]  COLUMN-LABEL "Agosto"
        DETALLE.ANIO2006[9]  COLUMN-LABEL "Setiem"
        DETALLE.ANIO2006[10] COLUMN-LABEL "Octubr"
        DETALLE.ANIO2006[11] COLUMN-LABEL "Noviem"
        DETALLE.ANIO2006[12] COLUMN-LABEL "Diciem"
        DETALLE.ANIO2007[1]  COLUMN-LABEL "Enero"
        DETALLE.ANIO2007[2]  COLUMN-LABEL "Febrer"
        DETALLE.ANIO2007[3]  COLUMN-LABEL "Marzo"
        DETALLE.ANIO2007[4]  COLUMN-LABEL "Abril"
        DETALLE.ANIO2007[5]  COLUMN-LABEL "Mayo"
        DETALLE.ANIO2007[6]  COLUMN-LABEL "Junio"
        DETALLE.ANIO2007[7]  COLUMN-LABEL "Julio"
        DETALLE.ANIO2007[8]  COLUMN-LABEL "Agosto"
        DETALLE.ANIO2007[9]  COLUMN-LABEL "Setiem"
        DETALLE.ANIO2007[10] COLUMN-LABEL "Octubre"
        DETALLE.ANIO2007[11] COLUMN-LABEL "Noviem"
        DETALLE.ANIO2007[12] COLUMN-LABEL "Diciem"
        DETALLE.ANIO2008[1]  COLUMN-LABEL "Enero"
        DETALLE.ANIO2008[2]  COLUMN-LABEL "Febrer"
        DETALLE.ANIO2008[3]  COLUMN-LABEL "Marzo"
        DETALLE.ANIO2008[4]  COLUMN-LABEL "Abril"
        DETALLE.ANIO2008[5]  COLUMN-LABEL "Mayo"
        DETALLE.ANIO2008[6]  COLUMN-LABEL "Junio"    
        WITH STREAM-IO NO-BOX WIDTH 320.
  END.

                  
