DEF STREAM cabecera.
DEF STREAM detalle.

OUTPUT STREAM cabecera TO c:\tmp\ccbccaja.txt.
OUTPUT STREAM detalle TO c:\tmp\ccbdcaja.txt.

    PUT STREAM cabecera UNFORMATTED
        'coddoc' '|'
        'nrodoc' '|'
        'fchdoc' '|'
        'usuario' '|'
        'tipo' '|'
        'impnac[1]' '|'
        'impnac[2]' '|'
        'impnac[3]' '|'
        'impnac[4]' '|'
        'impnac[5]' '|'
        'impnac[6]' '|'
        'impnac[7]' '|'
        'impnac[8]' '|'
        'impnac[9]' '|'
        'impnac[10]' '|'
        'impusa[1]' '|'
        'impusa[2]' '|'
        'impusa[3]' '|'
        'impusa[4]' '|'
        'impusa[5]' '|'
        'impusa[6]'  '|'
        'impusa[7]' '|'
        'impusa[8]' '|'
        'impusa[9]' '|'
        'impusa[10]' '|'
        'vuenac' '|'
        'vueusa' '|'
        'voucher[1]' '|'
        'voucher[2]' '|'
        'voucher[3]' '|'
        'voucher[4]' '|'
        'voucher[5]' '|'
        'voucher[6]' '|'
        'voucher[7]' '|'
        'voucher[8]' '|'
        'voucher[9]' '|'
        'voucher[10]' '|'
        'flgest' '|'
        'codcli' '|'
        'flgcie' '|'
        'fchcie' '|'
        'horcie' '|'
        'codmon' '|'
        'tpocmb' '|'
        'glosa' '|' 
        'codbco[1]' '|'
        'codbco[2]' '|'
        'codbco[3]' '|'
        'codbco[4]' '|'
        'codbco[5]' '|'
        'codbco[6]' '|'
        'codbco[7]' '|'
        'codbco[8]' '|'
        'codbco[9]' '|'
        'codbco[10]' '|'
        'coddiv' '|'
        'nomcli' '|'
        'codcaja'
        SKIP.
    PUT STREAM detalle
        'coddoc' '|'
        'nrodoc' '|'
        'fchdoc' '|'
        'codref ' '|'
        'nroref' '|'
        'imptot' '|'
        'fchdoc' '|'
        'codcli' '|'
        'codmon' '|'
        'tpocmb' '|'
        'coddiv'
        SKIP.

FOR EACH ccbccaja NO-LOCK WHERE codcia = 1
    AND LOOKUP(coddoc, 'I/C,E/C') > 0
    AND fchdoc >= 06/01/2012
    AND fchdoc <= TODAY - 1:
    PUT STREAM cabecera UNFORMATTED
        coddoc '|'
        nrodoc '|'
        fchdoc '|'
        usuario '|'
        tipo '|'
        impnac[1] '|'
        impnac[2] '|'
        impnac[3] '|'
        impnac[4] '|'
        impnac[5] '|'
        impnac[6] '|'
        impnac[7] '|'
        impnac[8] '|'
        impnac[9] '|'
        impnac[10] '|'
        impusa[1] '|'
        impusa[2] '|'
        impusa[3] '|'
        impusa[4] '|'
        impusa[5] '|'
        impusa[6] '|'
        impusa[7] '|'
        impusa[8] '|'
        impusa[9] '|'
        impusa[10] '|'
        vuenac '|'
        vueusa '|'
        voucher[1] '|'
        voucher[2] '|'
        voucher[3] '|'
        voucher[4] '|'
        voucher[5] '|'
        voucher[6] '|'
        voucher[7] '|'
        voucher[8] '|'
        voucher[9] '|'
        voucher[10] '|'
        flgest '|'
        codcli '|'
        flgcie '|'
        fchcie '|'
        horcie '|'
        codmon '|'
        tpocmb '|'
        glosa '|' 
        codbco[1] '|'
        codbco[2] '|'
        codbco[3] '|'
        codbco[4] '|'
        codbco[5] '|'
        codbco[6] '|'
        codbco[7] '|'
        codbco[8] '|'
        codbco[9] '|'
        codbco[10] '|'
        coddiv '|'
        nomcli '|'
        codcaja
        SKIP.
    FOR EACH ccbdcaja OF ccbccaja:
        PUT STREAM detalle UNFORMATTED
            ccbdcaja.coddoc '|'
            ccbdcaja.nrodoc '|'
            ccbdcaja.fchdoc '|'
            ccbdcaja.codref '|'
            ccbdcaja.nroref '|'
            ccbdcaja.imptot '|'
            ccbdcaja.fchdoc '|'
            ccbdcaja.codcli '|'
            ccbdcaja.codmon '|'
            ccbdcaja.tpocmb '|'
            ccbdcaja.coddiv
            SKIP.
    END.
END.
